'use strict';
const el=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const CHAPTER={unit:'elective1.ch2-1',title:'新陳代謝與酵素',version:1};
const KEY=`hanlin.${CHAPTER.unit}.v${CHAPTER.version}`;
const VIDEO_SRC='../教學影片/'+encodeURIComponent('選修生物(Ｉ)圖解PPT_CH2-1_新陳代謝與酵素_教學影片.mp4');
const ANIMATION_SRC='../'+encodeURIComponent('選修生物(Ｉ)圖解PPT_CH2-1_新陳代謝與酵素.mp4');
const REVEAL_N=5;
STAGES.forEach((s,i)=>{s.id=`b1-21-q${String(i+1).padStart(2,'0')}`;});
const INITIAL=()=>({schema:2,page:'intro',lesson:LEARN[0].id,question:STAGES[0].id,read:{},notes:{},drafts:{},results:{},theme:'light',font:0});
const VALID_DRAFTS=new WeakSet();
let ST=INITIAL(),PAGE='intro',LI=0,QI=0,SI=0,FT=null,FI=0,FL=[],FPLAY=false,SPLAY=null,selected=null,returnQuestion=false,saving=true,lastFocus=null;
try{const raw=localStorage.getItem(KEY);if(raw){const v=JSON.parse(raw);if(v?.schema===2){ST={...INITIAL(),...v};for(const k of ['read','notes','drafts','results'])if(!ST[k]||typeof ST[k]!=='object'||Array.isArray(ST[k]))ST[k]={};}}}catch(e){saving=false;}
LI=Math.max(0,LEARN.findIndex(x=>x.id===ST.lesson));QI=Math.max(0,STAGES.findIndex(x=>x.id===ST.question));
ST.theme=ST.theme==='dark'?'dark':'light';ST.font=[0,1,2].includes(ST.font)?ST.font:0;
function storageNotice(){el('save-status').hidden=false;el('save-status').textContent='此瀏覽器目前無法保存。請從學習診斷匯出結果與筆記，避免關頁後遺失。';}
function save(){ST.page=PAGE;ST.lesson=LEARN[LI].id;ST.question=STAGES[QI].id;try{localStorage.setItem(KEY,JSON.stringify(ST));saving=true;el('save-status').hidden=true;}catch(e){saving=false;storageNotice();}}
function result(s=STAGES[QI]){if(!ST.results[s.id]||typeof ST.results[s.id]!=='object')ST.results[s.id]={tries:0,errors:0,passed:false,revealed:false,tags:{}};return ST.results[s.id];}
function draft(s=STAGES[QI]){let d=ST.drafts[s.id];if(d&&typeof d==='object'&&VALID_DRAFTS.has(d))return d;if(!d||typeof d!=='object'||Array.isArray(d))d={};const valid=new Set((s.pieces||[]).map(p=>p.id));const place={};for(const x of s.slots||[])if(valid.has(d.place?.[x.id])&&!Object.values(place).includes(d.place[x.id]))place[x.id]=d.place[x.id];Object.assign(place,s.pre||{});const p=(d.pick||[]);const pick=Array.isArray(p)?p.filter(x=>Number.isInteger(x)&&x>=0&&x<(s.opts||[]).length):[];const fill=(s.rows||[]).map((r,i)=>{const v=d.fill?.[i];return v!==''&&v!=null&&Number.isInteger(+v)&&+v>=0&&+v<r.o.length?String(v):''});d={place,pick,fill,sub:Number.isInteger(d.sub)&&d.sub>=0&&d.sub<(s.rows||[]).length?d.sub:0};ST.drafts[s.id]=d;VALID_DRAFTS.add(d);return d;}
function captureDraft(){if(PAGE==='play')save();}
function navigate(page,index){
 if(document.fullscreenElement){document.exitFullscreen().then(()=>navigate(page,index)).catch(()=>navigateAfter(page,index));return;}
 navigateAfter(page,index);
}
function navigateAfter(page,index){
 captureDraft();flipStop();showStopPlay();el('teaching-video').pause();el('teaching-video').removeAttribute('src');el('teaching-video').load();document.body.classList.remove('play-mode','learn-mode');document.body.style.overflow='';
 PAGE=page;for(const id of ['intro','learn','play','done','video','show'])el(id).classList.toggle('hidden',id!==page);el('bar').classList.toggle('hidden',page!=='play');
 document.querySelectorAll('nav [data-page]').forEach(b=>{b.classList.toggle('current',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false')});
 if(page==='intro')renderHome();
 if(page==='learn'){document.body.classList.add('learn-mode');if(Number.isInteger(index))LI=Math.max(0,Math.min(LEARN.length-1,index));showLearn(LI);el('back-question').hidden=!returnQuestion;}
 if(page==='play'){document.body.classList.add('play-mode');if(Number.isInteger(index))QI=Math.max(0,Math.min(STAGES.length-1,index));showQuestion(QI);}
 if(page==='done')finish();
 if(page==='video')el('teaching-video').src=VIDEO_SRC;
 if(page==='show'){document.body.style.overflow='hidden';SI=Math.max(0,Math.min(DECK.length-1,index||0));showRender();el('shclose').focus({preventScroll:true});}
 save();window.scrollTo(0,0);requestAnimationFrame(fit);if(page!=='show'){const heading=el(page).querySelector('h1,h2');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}}
}
function renderHome(){const n=LEARN.filter(x=>ST.read[x.id]).length;el('reading-status').textContent=`已讀 ${n} / ${LEARN.length} 張圖解`;el('reading-progress').max=LEARN.length;el('reading-progress').value=n;el('continue-learn').textContent=n?`接續第 ${LI+1} 張 →`:'開始閱讀 →';el('lesson-count').textContent=`${LEARN.length} 張圖解 · 五個代謝主題`;el('question-count').textContent=`${STAGES.length} 關 · 4 關操作、2 關判讀、3 關原題`;el('slide-count').textContent=`${new Set(DECK.map(d=>d[1])).size} 頁 · ${DECK.length} 個逐步畫面`;}
function secOf(i){for(let j=i;j>=0;j--)if(LEARN[j].sec)return LEARN[j].sec;return 's1';}
function showLearn(i){
 LI=Math.max(0,Math.min(LEARN.length-1,i));flipStop();const L=LEARN[LI];ST.read[L.id]=true;
 const fig=L.fig?L.fig():flipBox(L.set)+(L.tb||[]).map(t=>tbImg(...t)).join('');
 el('lcard').innerHTML=`<div class="lhead"><span class="num">${String(LI+1).padStart(2,'0')} / ${LEARN.length}</span><span class="lsec">${SECN[secOf(LI)]}</span><h2>${L.t}</h2><span class="src">${L.src}</span></div><div class="lbody"><div class="lfig">${fig}</div><div class="ltext">${L.txt}<label class="note-label" for="lesson-note">思考筆記</label><p class="note-prompt">哪一項證據改變了你的解釋？還有什麼替代假說？</p><textarea class="lesson-note" id="lesson-note" placeholder="記下你的推論…">${esc(ST.notes[L.id]||'')}</textarea></div></div>`;
 el('lesson-note').oninput=e=>{ST.notes[L.id]=e.target.value;save()};
 let prev='';el('lesson-menu').innerHTML=LEARN.map((x,j)=>{const g=secOf(j),head=g!==prev?`<p class="menu-group">${SECN[g]}</p>`:'';prev=g;return head+`<button class="lesson-link ${j===LI?'current':''}" data-l="${j}" ${j===LI?'aria-current="step"':''}>${ST.read[x.id]?'✓':'○'} ${String(j+1).padStart(2,'0')}　${x.t}</button>`}).join('');
 el('lesson-menu').querySelectorAll('button').forEach(b=>b.onclick=()=>showLearn(+b.dataset.l));
 el('learn-position').textContent=`第 ${LI+1} / ${LEARN.length} 張`;el('fs-position').textContent=`${LI+1} / ${LEARN.length}`;el('read-count').textContent=`${Object.keys(ST.read).length}/${LEARN.length}`;
 for(const id of ['l-prev','fs-prev'])el(id).disabled=LI===0;for(const id of ['l-next','fs-next'])el(id).disabled=LI===LEARN.length-1;
 const f=el('flip');if(f)flipInit(f.dataset.set);
 el('lcard').querySelectorAll('[data-deck]').forEach(b=>b.onclick=()=>openShow(DECK.findIndex(d=>d[0]===b.dataset.deck)));
 prepareLesson();bindZoom(el('lcard'));save();if(document.fullscreenElement===el('learn-stage'))el('lcard').scrollTop=0;else window.scrollTo(0,0);fit();
}
function bindZoom(root){root.querySelectorAll('img.zoomable').forEach(img=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label','放大：'+img.alt);img.onclick=()=>zoom(img.src,img.alt);img.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();img.click()}}});}
function zoom(src,title){return openDialog(title,`<img src="${src}" alt="${esc(title)}">`);}
function openDialog(title,content){
 const previous=document.activeElement,d=document.createElement('dialog');d.setAttribute('aria-label',title);d.innerHTML=`<div class="dialog-header"><h2>${esc(title)}</h2><button aria-label="關閉放大視窗">關閉 ✕</button></div>${content}`;(document.fullscreenElement||document.body).appendChild(d);d.querySelector('button').onclick=()=>d.close();d.addEventListener('close',()=>{d.remove();if(previous?.isConnected)previous.focus({preventScroll:true})},{once:true});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});d.showModal();return d;
}
function openReferences(s){const refs=[...(s.preRefs||[]),...(s.refs||[])];const unique=refs.filter((x,i,a)=>a.findIndex(y=>y.src===x.src)===i);if(!unique.length){const L=LEARN[s.learn];return openShow(DECK.findIndex(d=>d[1]===+(L.src.match(/第 (\d+)/)?.[1]||22)));}openDialog('教材來源圖',unique.map(r=>`<figure><img src="${IMG[r.src]}" alt="${esc(r.cap)}"><figcaption>${esc(r.cap)}</figcaption></figure>`).join(''));}
function flipShow(i){FI=Math.max(0,Math.min(FL.length-1,i));el('fimg').src=IMG[FL[FI][0]];el('fimg').alt=FL[FI][2];el('fno').textContent=`${FI+1} / ${FL.length}`;el('fcap').textContent=FL[FI][2];fit();el('fdots').innerHTML=FL.map((x,j)=>`<button class="${j===FI?'on':''}" data-j="${j}" aria-label="第 ${j+1} 步：${esc(x[2])}"></button>`).join('');el('fdots').querySelectorAll('button').forEach(b=>b.onclick=()=>{flipStop();flipShow(+b.dataset.j)});}
function flipStop(){FPLAY=false;clearInterval(FT);FT=null;const b=el('fplay');if(b)b.textContent='▶ 自動播放';}
function flipStart(){FPLAY=true;FT=setInterval(()=>{if(FI>=FL.length-1){flipStop();return}flipShow(FI+1)},2600);el('fplay').textContent='⏸ 暫停';}
function flipInit(set){FL=FLIPS[set];flipShow(0);document.querySelectorAll('.fctl button').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==='play'){FPLAY?flipStop():(FI>=FL.length-1&&flipShow(0),flipStart());return;}flipStop();if(a==='show')openShow(DECK.findIndex(d=>d[0]===FL[FI][0]));else flipShow(a==='first'?0:FI+(a==='next'?1:-1));});el('fimg').classList.add('zoomable');}
function openShow(i){navigate('show',i>=0?i:0);}
function showRender(){const d=DECK[SI],same=DECK.filter(x=>x[1]===d[1]),k=same.findIndex(x=>x[0]===d[0]);el('shimg').src=IMG[d[0]];el('shimg').alt=`原PPT第${d[1]}頁第${k+1}步：${d[2]}`;el('shcap').textContent=d[2];el('shno').textContent=`PPT ${d[1]} / 25 · 本頁 ${k+1}/${same.length} 步 · 全部 ${SI+1}/${DECK.length}`;el('shsel').value=d[1];el('shprev').disabled=SI===0;el('shnext').disabled=SI===DECK.length-1;}
function showStopPlay(){clearInterval(SPLAY);SPLAY=null;el('shplay').textContent='▶ 自動播放';}
function showStep(d){showStopPlay();SI=Math.max(0,Math.min(DECK.length-1,SI+d));showRender();}
async function enterLearnFullscreen(){const stage=el('learn-stage');if(document.fullscreenElement===stage){await document.exitFullscreen();return;}if(stage.requestFullscreen){try{await stage.requestFullscreen();return;}catch(e){}}stage.classList.add('presentation');el('fs-exit').textContent='退出投影模式';el('learn-fullscreen').setAttribute('aria-pressed','true');fit();}
function exitLearnFullscreen(){el('learn-stage').classList.remove('presentation');if(document.fullscreenElement===el('learn-stage'))document.exitFullscreen();el('learn-fullscreen').setAttribute('aria-pressed','false');el('fs-exit').textContent='退出全螢幕';fit();}
function fullscreenSync(){const on=document.fullscreenElement===el('learn-stage');el('learn-fullscreen').setAttribute('aria-pressed',String(on));el('learn-fullscreen').textContent=on?'退出全螢幕':'全螢幕播放';el('shfs').setAttribute('aria-pressed',String(document.fullscreenElement===el('show')));el('shfs').textContent=document.fullscreenElement===el('show')?'退出全螢幕':'全螢幕';fit();}
function status(s){const r=ST.results[s.id],d=ST.drafts[s.id];return r?.revealed?'已揭露':r?.passed?'自行答對':d&&(Object.keys(d.place||{}).length>Object.keys(s.pre||{}).length||(d.pick||[]).length||(d.fill||[]).some(x=>x!==''))?'作答中':'未完成';}
function showQuestion(i){QI=i;selected=null;const s=STAGES[QI],r=result(s),d=draft(s);SLOTG=Object.fromEntries((s.slots||[]).map(x=>[x.id,x.group]));el('question-label').textContent=`第 ${QI+1} / ${STAGES.length} 關 · ${s.kind==='drag'?'操作':s.kind==='fill'?'表格判讀':s.kind==='multi'?'多選':'單選'}`;el('question-title').textContent=s.t;el('question-source').textContent=s.sub;el('question-text').textContent=s.q;el('question-hint').textContent=s.hint;el('question-hint').hidden=true;el('hint-toggle').setAttribute('aria-expanded','false');el('question-feedback').innerHTML='';el('question-explanation').hidden=true;el('question-panel').className=`q${QI+1}`;renderQuestion();if(r.passed)showPassed();updateBar();save();window.scrollTo(0,0);fit();}
function targetHTML(s,id,label){const d=draft(s),p=s.pieces.find(x=>x.id===d.place[id]),given=id in (s.pre||{}),n=s.slots.findIndex(x=>x.id===id)+1;return `<button class="target ${p?'filled':''} ${given?'given':''}" data-slot="${id}" ${given?'aria-disabled="true"':''} aria-label="第 ${n} 格${label?' '+esc(label):''}${p?'：'+esc(p.label):'，尚未放置'}"><span class="target-no">${n}</span><span>${p?esc(p.label):(label?esc(label)+' · 待放':'點選卡片後放這裡')}${given?'<small>已給答案 · 鎖定</small>':''}</span></button>`;}
function candidatesHTML(s){const d=draft(s),placed=new Set(Object.values(d.place)),available=s.pieces.filter(p=>!Object.values(s.pre||{}).includes(p.id));let perm=available.map((p,i)=>[p,(i*7+QI*11+3)%17]).sort((a,b)=>a[1]-b[1]).map(x=>x[0]);return `<aside class="candidate-area"><h3>選擇答案 <span style="font-size:12px;font-weight:400">${available.length} 張</span></h3><div class="candidates">${perm.map(p=>`<button class="candidate ${selected===p.id?'selected':''} ${placed.has(p.id)?'used':''}" data-piece="${p.id}" draggable="${!result(s).passed}" aria-pressed="${selected===p.id}"><span>${placed.has(p.id)?'✓ ':selected===p.id?'● ':''}${esc(p.label)}</span></button>`).join('')}</div><p class="candidate-help">點卡片，再點目標 · ✓ 已放入</p></aside>`;}
function renderQuestion(){const s=STAGES[QI],d=draft(s);let main='';if(s.kind==='drag'){
 const targets=s.slots.map(x=>`<div class="match-slot"><label>${esc(x.label)}</label>${targetHTML(s,x.id)}</div>`).join('');
 main=`${s.fig?`<div class="matching-figure"><img src="${IMG[s.fig]}" alt="${esc(s.t)} 教材圖" class="zoomable"><div class="match-list">${targets}</div></div>`:`<div class="sequence-grid">${targets}</div>`}`;
 el('question-panel').innerHTML=`<div class="work-layout"><div class="work-area">${main}</div>${candidatesHTML(s)}</div>`;
 const root=el('question-panel');root.querySelectorAll('[data-piece]').forEach(b=>{b.onclick=()=>choosePiece(b.dataset.piece);b.ondragstart=e=>{if(result(s).passed){e.preventDefault();return;}selected=b.dataset.piece;e.dataTransfer.setData('text/plain',selected);e.dataTransfer.effectAllowed='move';};});
 root.querySelectorAll('[data-slot]').forEach(b=>{b.onclick=()=>putPiece(b.dataset.slot);b.ondragover=e=>{if(!(b.dataset.slot in (s.pre||{}))&&!result(s).passed)e.preventDefault();};b.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(s.pieces.some(p=>p.id===id))selected=id;putPiece(b.dataset.slot);};});bindZoom(root);
 }else if(s.kind==='fill'){
 const j=d.sub,r=s.rows[j],perm=r.o.map((_,i)=>i);if(j%2)perm.reverse();else perm.push(perm.shift());
 main=`<div class="fill-layout"><div class="reference-rail"><img src="${IMG[s.fig]}" alt="${esc(s.t)} 完整參考圖" class="zoomable"><p class="reference-caption">${esc(s.sub)} · 點圖放大</p></div><div class="fill-subquestion"><div class="fill-navigation" aria-label="判讀小題">${s.rows.map((x,k)=>`<button data-sub="${k}" class="${k===j?'current':''}" ${k===j?'aria-current="step"':''} aria-label="第 ${k+1} 小題 ${esc(x.q)}${d.fill[k]!==''?'，已作答':''}">${k+1}${d.fill[k]!==''?' ✓':''}</button>`).join('')}</div><h3>${j+1} / ${s.rows.length} · ${esc(r.q)}</h3><div class="fill-options">${perm.map((oi,k)=>`<button class="fill-option ${d.fill[j]===String(oi)?'selected':''}" data-fill="${oi}" aria-pressed="${d.fill[j]===String(oi)}"><span class="letter">${'ABC'[k]}</span><span>${esc(r.o[oi])}</span></button>`).join('')}</div><div class="fill-step-controls"><button data-step="-1" ${j===0?'disabled':''}>上一小題</button><span>已選 ${d.fill.filter(x=>x!=='').length} / ${s.rows.length} 小題</span><button data-step="1" ${j===s.rows.length-1?'disabled':''}>下一小題</button></div></div></div>`;
 el('question-panel').innerHTML=main;
 el('question-panel').querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>{d.sub=+b.dataset.sub;save();renderQuestion();fit()});
 el('question-panel').querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{d.sub+=+b.dataset.step;save();renderQuestion();fit()});
 el('question-panel').querySelectorAll('[data-fill]').forEach(b=>{b.disabled=result(s).passed;b.onclick=()=>{d.fill[j]=b.dataset.fill;clearFeedback();save();renderQuestion();updateBar();fit();};});bindZoom(el('question-panel'));
 }else{
 const perm=s.opts.map((_,i)=>i);el('question-panel').innerHTML=`<div class="option-list">${perm.map((i,j)=>`<button class="option ${d.pick.includes(i)?'selected':''}" data-opt="${i}" aria-pressed="${d.pick.includes(i)}"><span class="letter">${'ABCDEF'[j]}</span><span>${esc(s.opts[i].t)}</span></button>`).join('')}</div>`;if(s.fig){el('question-panel').innerHTML=`<div class="choice-layout"><div>${el('question-panel').innerHTML}</div><figure><img src="${IMG[s.fig]}" alt="${esc(s.t)} 教材參考圖" class="zoomable"><figcaption>原PPT第${s.sourceSlide}頁原圖 · 點圖放大</figcaption></figure></div>`;}bindZoom(el('question-panel'));el('question-panel').querySelectorAll('[data-opt]').forEach(b=>{b.disabled=result(s).passed;b.onclick=()=>{const i=+b.dataset.opt;if(s.kind==='single')d.pick=[i];else d.pick=d.pick.includes(i)?d.pick.filter(x=>x!==i):[...d.pick,i];clearFeedback();save();renderQuestion();updateBar();fit();}});
 }
 if(result(s).passed)el('question-panel').querySelectorAll('button:not(.zoomable),select').forEach(b=>{if(b.matches('[data-piece],[data-slot],[data-opt],[data-fill],select'))b.disabled=true;});
}
function clearFeedback(){el('question-feedback').innerHTML='';el('question-explanation').hidden=true;document.querySelectorAll('.bad,.wrong').forEach(x=>x.classList.remove('bad','wrong'));}
function choosePiece(id){const s=STAGES[QI];if(result(s).passed)return;selected=selected===id?null:id;const focusId=id;renderQuestion();el('question-panel').querySelector(`[data-piece="${focusId}"]`)?.focus({preventScroll:true});updateBar();fit();}
function putPiece(slot){const s=STAGES[QI];if(result(s).passed||slot in (s.pre||{}))return;const d=draft(s);if(selected){for(const k in d.place)if(d.place[k]===selected)delete d.place[k];d.place[slot]=selected;selected=null;}else if(d.place[slot])delete d.place[slot];else{el('barmsg').textContent='先選擇一張答案卡，再放進目標。';return;}clearFeedback();save();renderQuestion();el('question-panel').querySelector(`[data-slot="${slot}"]`)?.focus({preventScroll:true});updateBar();fit();}
function updateBar(){const s=STAGES[QI],r=result(s),d=draft(s),n=STAGES.filter(x=>ST.results[x.id]?.passed).length;el('q-jump').innerHTML=STAGES.map((x,i)=>`<option value="${i}">${i+1}. ${esc(x.t)} · ${status(x)}</option>`).join('');el('q-jump').value=QI;drawStageTrack();el('nav-status').textContent=`完成 ${n}/${STAGES.length}`;el('barmsg').textContent=r.passed?(r.revealed?'已揭露答案':'✓ 自行答對')+' · '+r.errors+' 次有效錯誤':selected?'已選取卡片 · 點目標放置':s.kind==='drag'?`已放 ${Object.keys(d.place).length}/${s.slots.length} 格`:`已選 ${s.kind==='fill'?d.fill.filter(x=>x!=='').length:d.pick.length}${s.kind==='fill'?'/'+s.rows.length+' 列':' 項'}`;el('prev-btn').disabled=QI===0;el('check-btn').disabled=r.passed;el('reset-btn').disabled=r.passed;el('skip-btn').textContent=QI===STAGES.length-1?'看診斷 →':'下一題 →';}
function check(){const s=STAGES[QI],r=result(s),d=draft(s);if(r.passed)return;r.tries++;
 const complete=s.kind==='drag'?s.slots.every(x=>d.place[x.id]):s.kind==='fill'?d.fill.every(x=>x!==''):d.pick.length>0;
 if(!complete){el('question-feedback').innerHTML='<div class="feedback">請先完成作答；空白或不完整提交不計有效錯誤。</div>';save();fit();return;}
 let answer;if(s.kind==='drag'){SLOTG=Object.fromEntries(s.slots.map(x=>[x.id,x.group]));answer=s.check(Object.fromEntries(s.slots.map(x=>[x.id,s.pieces.find(p=>p.id===d.place[x.id])])));}else if(s.kind==='fill'){const bad=s.rows.map((x,i)=>d.fill[i]!=='0'?i:-1).filter(i=>i>=0);answer={ok:!bad.length,msg:`有 ${bad.length} 列需要再檢查。比較活化能、構形、環境與輔因子的角色。`,tags:[...new Set(bad.map(i=>s.rows[i].tag))]};el('question-panel').querySelectorAll('[data-sub]').forEach((x,i)=>x.classList.toggle('bad',bad.includes(i)));}else{const right=s.opts.map((x,i)=>x.ok?i:-1).filter(i=>i>=0);answer={ok:d.pick.length===right.length&&right.every(i=>d.pick.includes(i)),msg:'檢查每個選項的範圍與用語，並留意有沒有漏選。',tags:[...new Set(s.opts.filter((x,i)=>x.ok!==d.pick.includes(i)).map(x=>x.tag).filter(Boolean))]};}
 if(answer.ok){r.passed=true;r.revealed=false;showPassed();}else{r.errors++;for(const t of answer.tags||[])r.tags[t]=(r.tags[t]||0)+1;if(r.errors>=REVEAL_N){r.passed=true;r.revealed=true;if(s.kind==='drag')d.place={...s.sol};else if(s.kind==='fill')d.fill=s.rows.map(()=> '0');else d.pick=s.opts.map((x,i)=>x.ok?i:-1).filter(i=>i>=0);save();renderQuestion();showPassed();}else{el('question-feedback').innerHTML=`<div class="feedback error">再試一次 · 有效錯誤 ${r.errors}/${REVEAL_N}<button id="error-help">查看思考回饋</button><span class="feedback-tags">${(answer.tags||[]).map(t=>TAGS[t]?.[0]||t).join('、')}</span></div>`;el('error-help').onclick=()=>openDialog('思考回饋',`<p>${esc(answer.msg||'重新比對各組實驗的條件與結果。')}</p><p>${(answer.tags||[]).map(t=>TAGS[t]?.[0]||t).join('、')}</p>`);}}
 save();updateBar();fit();}
function showPassed(){const s=STAGES[QI],r=result(s);el('question-feedback').innerHTML=`<div class="feedback correct">${r.revealed?'已揭露正確答案；此關記錄為「揭露」，不計自行答對。':'✓ 正確！你已完成這一關。'}<button id="explanation-toggle" aria-expanded="false">展開解析</button></div>`;el('question-explanation').innerHTML=`<p>${s.why}</p><div class="explanation-refs">${(s.refs||[]).map(x=>`<button data-ref="${x.src}">${x.cap}</button>`).join('')}</div>`;el('question-explanation').querySelectorAll('button').forEach(b=>b.onclick=()=>zoom(IMG[b.dataset.ref],b.textContent));el('explanation-toggle').onclick=()=>{const on=el('question-explanation').hidden;el('question-explanation').hidden=!on;el('explanation-toggle').setAttribute('aria-expanded',String(on));el('explanation-toggle').textContent=on?'收起解析':'展開解析';fit();};el('question-panel').querySelectorAll('[data-opt]').forEach(b=>{b.classList.toggle('correct',s.opts[+b.dataset.opt].ok);b.setAttribute('aria-pressed',String(draft(s).pick.includes(+b.dataset.opt)));});el('question-panel').querySelectorAll('[data-piece],[data-slot],[data-opt],[data-fill],select').forEach(b=>b.disabled=true);}
function resetQuestion(){if(result().passed)return;delete ST.drafts[STAGES[QI].id];selected=null;clearFeedback();save();renderQuestion();updateBar();fit();}
function finish(){const total=STAGES.length,completed=STAGES.filter(s=>ST.results[s.id]?.passed).length,revealed=STAGES.filter(s=>ST.results[s.id]?.revealed).length,errors=STAGES.reduce((n,s)=>n+(ST.results[s.id]?.errors||0),0);const tags={};for(const s of STAGES)for(const [k,v] of Object.entries(ST.results[s.id]?.tags||{}))tags[k]=(tags[k]||0)+v;
 el('done').innerHTML=`<div class="report"><div class="page-toolbar"><button class="btn ghost" data-home>回到首頁</button><button class="btn" id="resume-quiz">接續練習</button></div><p class="eyebrow">LEARNING JOURNAL / 學習紀錄</p><h1>用證據檢查自己的理解</h1><p>完成 ${completed}/${total} 關。${completed<total?'尚有 '+(total-completed)+' 關未完成；診斷依目前作答紀錄呈現。':'全部關卡已完成。'}</p><div class="stats"><div class="stat"><strong>${completed-revealed}</strong><span>自行答對</span></div><div class="stat"><strong>${revealed}</strong><span>揭露答案</span></div><div class="stat"><strong>${total-completed}</strong><span>尚未完成</span></div><div class="stat"><strong>${errors}</strong><span>有效錯誤次數</span></div></div><h2>逐關紀錄</h2>${STAGES.map((s,i)=>`<div class="report-row"><span>${String(i+1).padStart(2,'0')}　${s.t}</span><span class="row-state">${status(s)} · 提交 ${ST.results[s.id]?.tries||0} 次／有效錯誤 ${ST.results[s.id]?.errors||0} 次</span><button data-review="${i}">回訪</button></div>`).join('')}<h2>值得回頭看的概念</h2>${Object.keys(tags).length?Object.keys(tags).sort((a,b)=>tags[b]-tags[a]).map(t=>`<div class="diagnostic"><b>${TAGS[t][0]} · 觸發 ${tags[t]} 次</b><p>${TAGS[t][1]}</p><p class="report-sources">${TAGS[t][2]}</p><button class="btn ghost" data-concept="${t}">回看相關圖解</button></div>`).join(''):'<p>目前沒有記錄到概念錯誤。'+(completed<total?'尚未完成所有題目，不據此推估學習能力。':'')+'</p>'}<h2>我的思考筆記</h2>${LEARN.filter(x=>ST.notes[x.id]?.trim()).map(x=>`<div class="note-export"><b>${x.t}</b>\n${esc(ST.notes[x.id])}</div>`).join('')||'<p>尚未記下筆記。</p>'}<div class="report-actions"><button class="btn" id="export-json">匯出學習紀錄 JSON</button><button class="btn ghost" id="export-text">匯出文字與筆記</button><button class="btn ghost" id="print-report">列印診斷</button></div><p class="report-sources">教材來源：翰林選修生物Ⅰ 2-1；課本 PDF 5 頁（印刷 P70–P74）、原 PPT 25 頁。圖解與題目可回訪對應來源。紀錄僅儲存在此瀏覽器，未傳送到外部伺服器。</p></div>`;
 el('done').querySelector('[data-home]').onclick=()=>navigate('intro');el('resume-quiz').onclick=()=>navigate('play',Math.max(0,STAGES.findIndex(s=>!ST.results[s.id]?.passed)));el('done').querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>navigate('play',+b.dataset.review));const conceptMap=CONCEPT_MAP;el('done').querySelectorAll('[data-concept]').forEach(b=>b.onclick=()=>navigate('learn',conceptMap[b.dataset.concept]));el('export-json').onclick=()=>download('代謝與酵素驛站_學習紀錄.json',JSON.stringify({chapter:CHAPTER,exportedAt:new Date().toISOString(),...ST},null,2),'application/json');el('export-text').onclick=()=>download('代謝與酵素驛站_筆記與診斷.txt',reportText(),'text/plain');el('print-report').onclick=()=>window.print();save();}
function reportText(){return CHAPTER.title+'｜學習紀錄\n'+new Date().toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})+'\n\n'+STAGES.map((s,i)=>`${i+1}. ${s.t}｜${status(s)}｜提交 ${ST.results[s.id]?.tries||0} 次｜有效錯誤 ${ST.results[s.id]?.errors||0} 次\n來源：${s.sub}`).join('\n\n')+'\n\n思考筆記\n'+LEARN.filter(x=>ST.notes[x.id]).map(x=>x.t+'\n來源：'+x.src+'\n'+ST.notes[x.id]).join('\n\n')+'\n\n教材：翰林選修生物Ⅰ，課本 P70–P74；PPT 25 頁。';}
function download(name,body,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([body],{type:type+';charset=utf-8'}));a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}

function drawStageTrack(){
 const track=el('stage-track');track.style.setProperty('--stage-count',STAGES.length);track.innerHTML=STAGES.map((s,i)=>`<button data-stage="${i}" ${i===QI?'aria-current="step"':''} aria-label="第 ${i+1} 關：${esc(s.t)}，${status(s)}" title="${esc(s.t)} · ${status(s)}">${i+1}<span class="stage-state">${ST.results[s.id]?.revealed?'揭露':ST.results[s.id]?.passed?'✓':status(s)==='作答中'?'•':''}</span></button>`).join('');
 track.querySelectorAll('button').forEach(b=>b.onclick=()=>showQuestion(+b.dataset.stage));
}
let READING=null,tableState=null,resultObserver=null;
function readingBlocks(node){
 const blocks=[];for(const child of [...node.childNodes]){
  if(child.nodeType===3){if(child.textContent.trim()){const p=document.createElement('p');p.textContent=child.textContent;blocks.push(p);}continue;}
  if(child.matches('ul,ol'))for(const li of child.children){const list=document.createElement(child.tagName);list.append(li.cloneNode(true));blocks.push(list);}
  else blocks.push(child.cloneNode(true));
 }return blocks;
}
function prepareLesson(){
 resultObserver?.disconnect();resultObserver=null;tableState=null;
 const fig=el('lcard').querySelector('.lfig'),text=el('lcard').querySelector('.ltext'),core=document.createElement('div'),ref=document.createElement('div'),notes=document.createElement('div');
 for(const child of [...text.childNodes]){if(child.nodeType===1&&child.matches('.note-label,.note-prompt,.lesson-note'))notes.append(child);else if(child.nodeType===1&&child.matches('.quote'))ref.append(child);else core.append(child);}
 const canvas=document.createElement('div'),tools=document.createElement('div');canvas.className='figure-canvas';tools.className='figure-tools';
 for(const child of [...fig.children]){
  if(child.matches('.cap')){ref.append(child);continue;}
  if(child.matches('details.tbx')){const img=child.querySelector('img'),b=document.createElement('button');b.textContent='課本原圖';b.title=img.alt;b.onclick=()=>zoom(img.src,img.alt);tools.append(b);continue;}
  if(child.matches('.fctl,.fdots,button'))tools.append(child);else canvas.append(child);
 }
 fig.replaceChildren(canvas,tools);const groups=[{name:'教學重點',nodes:readingBlocks(core)},{name:'原文與圖說',nodes:readingBlocks(ref)},{name:'思考筆記',notes}];
 if(!groups[1].nodes.length){const p=document.createElement('p');p.className='cap';p.textContent=LEARN[LI].src;groups[1].nodes=[p];}
 const sim=canvas.querySelector('#sim');if(sim){
  const result=sim.querySelector('#simres'),layout=document.createElement('div');layout.className='sim-layout';layout.append(sim.querySelector('svg'),sim.querySelector('.simctl'));sim.replaceChildren(layout);
  result.hidden=true;fig.append(result);groups.push({name:'實驗結果',nodes:[document.createElement('p')]});
  resultObserver=new MutationObserver(()=>{if(!READING||LI!==SIM_CARD)return;READING.groups[3].nodes=readingBlocks(result);if(!READING.groups[3].nodes.length){const p=document.createElement('p');p.textContent=result.textContent;READING.groups[3].nodes=[p];}READING.cache='';if(result.textContent.includes('結果')||result.textContent.includes('無法確定'))selectReadingTab(3);fit();});
  groups[3].nodes[0].textContent=result.textContent;resultObserver.observe(result,{childList:true,subtree:true,characterData:true});
 }
 READING={groups,tab:0,indices:groups.map(()=>0),pages:[],cache:''};
 const tabs=document.createElement('div');tabs.className='reading-tabs';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','圖解解說分頁');
 groups.forEach((g,i)=>{const b=document.createElement('button');b.id='reading-tab-'+i;b.textContent=g.name;b.setAttribute('role','tab');b.setAttribute('aria-controls','reading-pane-'+i);b.onclick=()=>selectReadingTab(i);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();e.stopPropagation();const n=e.key==='Home'?0:e.key==='End'?groups.length-1:(i+(e.key==='ArrowRight'?1:-1)+groups.length)%groups.length;selectReadingTab(n);tabs.children[n].focus();}};tabs.append(b);});
 text.replaceChildren(tabs);groups.forEach((g,i)=>{const pane=document.createElement('section');pane.className='reading-pane'+(g.notes?' notes-pane':'');pane.id='reading-pane-'+i;pane.setAttribute('role','tabpanel');pane.setAttribute('aria-labelledby','reading-tab-'+i);if(g.notes){pane.append(...g.notes.childNodes);pane.querySelector('textarea').oninput=e=>{ST.notes[LEARN[LI].id]=e.target.value;save();};}else{pane.innerHTML='<div class="reading-body"></div><div class="reading-pager"><button aria-label="上一頁解說">←</button><span aria-live="polite"></span><button aria-label="下一頁解說">→</button></div>';const buttons=pane.querySelectorAll('button');buttons[0].onclick=()=>stepReading(-1);buttons[1].onclick=()=>stepReading(1);}text.append(pane);});
 const table=canvas.querySelector('.cmp2');if(table){canvas.classList.add('table-canvas');const rows=[...table.rows].slice(1),pager=document.createElement('div');pager.className='table-pager';pager.innerHTML='<button>← 前組</button><span></span><button>後組 →</button><button>完整表格 ↗</button>';tools.append(pager);tableState={table,rows,index:0,count:1,pager,original:table.outerHTML};const b=pager.querySelectorAll('button');b[0].onclick=()=>{tableState.index--;fitLessonTable();};b[1].onclick=()=>{tableState.index++;fitLessonTable();};b[2].onclick=()=>openDialog('完整實驗設計比較表',tableState.original);}
 el('lcard').querySelectorAll('img').forEach(img=>img.addEventListener('load',fit,{once:true}));selectReadingTab(0);
}
function selectReadingTab(i){if(!READING)return;READING.tab=i;el('lcard').querySelectorAll('.reading-tabs button').forEach((b,j)=>{b.setAttribute('aria-selected',String(i===j));b.tabIndex=i===j?0:-1;});el('lcard').querySelectorAll('.reading-pane').forEach((p,j)=>p.hidden=i!==j);READING.cache='';fit();}
function stepReading(d){if(!READING)return;const i=READING.tab;READING.indices[i]=Math.max(0,Math.min((READING.pages[i]?.length||1)-1,READING.indices[i]+d));renderReading();}
function splitBlock(node,body){
 // Range fragments keep inline emphasis and every character when a long paragraph needs another page.
 const length=node.textContent.length;if(!length)return [node];const walker=document.createTreeWalker(node,NodeFilter.SHOW_TEXT),texts=[];let n,offset=0;while(n=walker.nextNode()){texts.push({node:n,start:offset,end:offset+n.length});offset+=n.length;}
 function fragment(a,b){const range=document.createRange(),start=texts.find(t=>t.end>a),end=texts.find(t=>t.end>=b);range.setStart(start.node,a-start.start);range.setEnd(end.node,b-end.start);const clone=node.cloneNode(false);clone.append(range.cloneContents());return clone;}
 const parts=[];let from=0;while(from<length){let lo=from+1,hi=length,best=lo;while(lo<=hi){const mid=(lo+hi)>>1,c=fragment(from,mid);body.replaceChildren(c);if(body.scrollHeight<=body.clientHeight+1){best=mid;lo=mid+1;}else hi=mid-1;}
  if(best<length){const s=node.textContent.slice(from,best),breakAt=Math.max(s.lastIndexOf('。'),s.lastIndexOf('；'),s.lastIndexOf('，'));if(breakAt>Math.max(20,s.length*.55))best=from+breakAt+1;}
  parts.push(fragment(from,best));from=best;
 }body.replaceChildren();return parts;
}
function paginateReading(){
 if(!READING)return;const i=READING.tab,g=READING.groups[i];if(g.notes)return;const pane=el('reading-pane-'+i),body=pane.querySelector('.reading-body'),pager=pane.querySelector('.reading-pager');pager.hidden=false;
 const key=[i,body.clientWidth,body.clientHeight,ST.font,innerWidth>900].join(':');if(READING.cache===key){renderReading();return;}
 const pages=[[]];body.replaceChildren();
 if(innerWidth<=900){pages[0]=g.nodes.map(x=>x.cloneNode(true));}
 else for(const original of g.nodes){let node=original.cloneNode(true);body.append(node);if(body.scrollHeight<=body.clientHeight+1){pages.at(-1).push(node);continue;}node.remove();if(pages.at(-1).length){pages.push([]);body.replaceChildren();}body.append(node);if(body.scrollHeight<=body.clientHeight+1){pages.at(-1).push(node);continue;}
  body.replaceChildren();const parts=splitBlock(original,body);for(const part of parts){if(pages.at(-1).length)pages.push([]);pages.at(-1).push(part);}body.replaceChildren(...pages.at(-1));
 }
 READING.pages[i]=pages;READING.cache=key;READING.indices[i]=Math.min(READING.indices[i],pages.length-1);renderReading();
}
function renderReading(){if(!READING)return;const i=READING.tab,pages=READING.pages[i];if(!pages)return;const pane=el('reading-pane-'+i),j=READING.indices[i];pane.querySelector('.reading-body').replaceChildren(...pages[j].map(x=>x.cloneNode(true)));const pager=pane.querySelector('.reading-pager');pager.hidden=pages.length<2;pager.querySelector('span').textContent=`${j+1} / ${pages.length} 頁`;const b=pager.querySelectorAll('button');b[0].disabled=j===0;b[1].disabled=j===pages.length-1;bindZoom(pane);}
function fitLessonTable(){if(!tableState)return;const {table,rows,pager}=tableState,canvas=table.closest('.figure-canvas');rows.forEach(r=>r.hidden=false);if(innerWidth<=900){tableState.count=rows.length;tableState.index=0;}else{const head=table.rows[0].getBoundingClientRect().height,room=canvas.clientHeight-head-2;let height=0,count=0;for(const row of rows){const h=row.getBoundingClientRect().height;if(height+h>room&&count)break;height+=h;count++;}tableState.count=Math.max(1,count);tableState.index=Math.max(0,Math.min(Math.ceil(rows.length/tableState.count)-1,tableState.index));}
 const {count,index}=tableState;rows.forEach((r,i)=>r.hidden=i<index*count||i>=(index+1)*count);pager.querySelector('span').textContent=`${index+1} / ${Math.ceil(rows.length/count)} 組`;const b=pager.querySelectorAll('button');b[0].disabled=index===0;b[1].disabled=(index+1)*count>=rows.length;
}
function fitLesson(){
 const stage=el('learn-stage'),card=el('lcard'),root=document.documentElement,fs=document.fullscreenElement===stage||stage.classList.contains('presentation');
 if(innerWidth>900){const top=fs?12:card.getBoundingClientRect().top,nav=(fs?stage.querySelector('.fs-controls'):el('learn').querySelector('.lnav')).getBoundingClientRect().height,head=card.querySelector('.lhead').getBoundingClientRect().height,cardH=Math.max(230,innerHeight-top-nav-26);root.style.setProperty('--lesson-card-height',cardH+'px');root.style.setProperty('--lesson-body-height',(cardH-head-2)+'px');}
 paginateReading();fitLessonTable();
}

let fitPending=false;
function fit(){if(fitPending)return;fitPending=true;requestAnimationFrame(()=>{fitPending=false;const bar=el('bar'),h=bar.classList.contains('hidden')?0:Math.ceil(bar.getBoundingClientRect().height);if(document.documentElement.style.getPropertyValue('--barh')!==h+'px')document.documentElement.style.setProperty('--barh',h+'px');
 if(PAGE==='learn')fitLesson();
 if(PAGE==='play'&&innerWidth>900){const panel=el('question-panel'),top=panel.getBoundingClientRect().top,fb=el('question-feedback').getBoundingClientRect().height,available=innerHeight-h-top-fb-26;
 const layout=panel.querySelector('.fill-layout'),rail=panel.querySelector('.reference-rail'),img=rail?.querySelector('img');if(img){const ratio=img.naturalWidth/img.naturalHeight||1;for(let pass=0;pass<3;pass++){const caption=rail.querySelector('p').getBoundingClientRect().height+8,width=Math.min(Math.min(STAGES[QI].imageWidth||440,panel.clientWidth-380),Math.max(140,(available-caption)*ratio));if(Math.abs(rail.getBoundingClientRect().width-width)<.1)break;layout.style.setProperty('--reference-width',width+'px');}}
 const match=panel.querySelector('.matching-figure img');if(match){match.style.maxHeight=Math.max(140,available-30)+'px';}
 const choice=panel.querySelector('.choice-layout img');if(choice){choice.style.maxHeight=Math.max(140,available-30)+'px';}
 } });}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{returnQuestion=PAGE==='play'&&b.dataset.page==='learn';navigate(b.dataset.page)});
el('continue-learn').onclick=()=>navigate('learn',LI);el('back-question').onclick=()=>navigate('play',QI);el('learn-fullscreen').onclick=enterLearnFullscreen;el('fs-exit').onclick=exitLearnFullscreen;
for(const id of ['l-prev','fs-prev'])el(id).onclick=()=>LI>0&&showLearn(LI-1);for(const id of ['l-next','fs-next'])el(id).onclick=()=>LI<LEARN.length-1&&showLearn(LI+1);
el('related-slide').onclick=()=>openShow(DECK.findIndex(d=>d[1]===+(LEARN[LI].src.match(/第 (\d+)/)?.[1]||1)));
el('hint-toggle').setAttribute('aria-haspopup','dialog');el('hint-toggle').onclick=()=>{el('hint-toggle').setAttribute('aria-expanded','true');const d=openDialog('思考提示',`<p>${esc(STAGES[QI].hint)}</p>`);d.addEventListener('close',()=>el('hint-toggle').setAttribute('aria-expanded','false'),{once:true});};el('reference-btn').onclick=()=>openReferences(STAGES[QI]);el('question-learn').onclick=()=>{returnQuestion=true;navigate('learn',STAGES[QI].learn)};el('q-jump').onchange=e=>showQuestion(+e.target.value);el('prev-btn').onclick=()=>QI>0&&showQuestion(QI-1);el('skip-btn').onclick=()=>QI<STAGES.length-1?showQuestion(QI+1):navigate('done');el('check-btn').onclick=check;el('reset-btn').onclick=resetQuestion;el('finish-btn').onclick=()=>navigate('done');
el('shsel').innerHTML=[...new Set(DECK.map(d=>d[1]))].map(n=>`<option value="${n}">第 ${n} 頁 · ${esc(DECK.find(d=>d[1]===n)[2].slice(0,22))}</option>`).join('');el('shsel').onchange=e=>{showStopPlay();SI=DECK.findIndex(d=>d[1]===+e.target.value);showRender();};el('shprev').onclick=()=>showStep(-1);el('shnext').onclick=()=>showStep(1);el('shplay').onclick=()=>{if(SPLAY)showStopPlay();else{if(SI===DECK.length-1)SI=0;showRender();SPLAY=setInterval(()=>{if(SI>=DECK.length-1){showStopPlay();return;}SI++;showRender()},2600);el('shplay').textContent='⏸ 暫停';}};el('shfs').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else el('show').requestFullscreen?.().catch(()=>{el('shfs').textContent='此瀏覽器不支援原生全螢幕'})};el('shclose').onclick=()=>navigate('intro');
el('theme-toggle').onclick=()=>{ST.theme=ST.theme==='dark'?'light':'dark';applyPreferences();save();};el('font-toggle').onclick=()=>{ST.font=(ST.font+1)%3;applyPreferences();save();fit();};function applyPreferences(){document.documentElement.dataset.theme=ST.theme;document.documentElement.style.setProperty('--text',[20,22,24][ST.font]+'px');document.documentElement.dataset.font=ST.font;el('theme-toggle').setAttribute('aria-pressed',String(ST.theme==='dark'));el('font-toggle').title='文字大小 '+[20,22,24][ST.font]+'px';}
document.addEventListener('fullscreenchange',fullscreenSync);document.addEventListener('keydown',e=>{if(e.isComposing||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if(document.querySelector('dialog[open]'))return;const fs=document.fullscreenElement===el('learn-stage')||el('learn-stage').classList.contains('presentation');if(fs){if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();if(LI<LEARN.length-1)showLearn(LI+1);}else if(['ArrowLeft','ArrowUp','PageUp','Backspace'].includes(e.key)){e.preventDefault();if(LI>0)showLearn(LI-1);}else if(e.key==='Escape')exitLearnFullscreen();return;}if(PAGE==='show'){if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();showStep(1);}else if(['ArrowLeft','ArrowUp','PageUp','Backspace'].includes(e.key)){e.preventDefault();showStep(-1);}else if(e.key==='Escape')navigate('intro');else if(e.key==='Home'){SI=0;showRender()}else if(e.key==='End'){SI=DECK.length-1;showRender()}return;}if(PAGE==='learn'&&el('flip')){if(e.key==='ArrowRight'){e.preventDefault();flipStop();flipShow(FI+1)}if(e.key==='ArrowLeft'){e.preventDefault();flipStop();flipShow(FI-1)}}});
el('learn-stage').addEventListener('contextmenu',e=>{if(document.fullscreenElement===el('learn-stage')||el('learn-stage').classList.contains('presentation')){e.preventDefault();if(LI<LEARN.length-1)showLearn(LI+1)}});
window.addEventListener('resize',fit);window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden){flipStop();showStopPlay();save();}});new ResizeObserver(fit).observe(el('bar'));
el('slide-text').onclick=()=>openDialog('原PPT第'+DECK[SI][1]+'頁原文',`<p>${esc(CONTENT.pptText[DECK[SI][1]])}</p>`);el('hero-image').src=IMG[DECK.filter(d=>d[1]===11).at(-1)[0]];el('video-external').href=VIDEO_SRC;el('raw-animation').onclick=()=>{const d=openDialog('原始簡報動畫',`<video controls autoplay playsinline style="width:100%" src="${ANIMATION_SRC}"></video>`);d.addEventListener('close',()=>d.querySelector('video')?.pause(),{once:true});};applyPreferences();const start=['learn','play','done'].includes(ST.page)?ST.page:'intro';navigate(start);if(!saving)storageNotice();
